### ISSUE TITLE
니아

### ISSUE THREAD

**Issue by yeongsun** [yeongsunpark/cute#7]
일단 cw에서 받은 엑셀 파일을 하나의 텍스트 파일로 만들기 ( 5만건)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 14: invalid start byte

**Comment by yeongsunpark** [comment]
exec, eval 해서 같은 스크립트 안의 클래스, 함수 이용함

**Comment by yeongsun** [comment]
exec("j{} = SquadDb()".format(n))
    eval("j{}.connect_db('{}')".format(n, table_name)) < -이런 느낌.
